// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSCDavgvVS2Ix0M_9siwzUVNbTcaN1K90',
    appId: '1:338750312653:web:32391801da3ac597415984',
    messagingSenderId: '338750312653',
    projectId: 'chat-83727',
    authDomain: 'chat-83727.firebaseapp.com',
    storageBucket: 'chat-83727.firebasestorage.app',
    measurementId: 'G-1TBSW89Z18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMx2AJH1zWqxLJnCf5FEnDGzfrGuGkUXw',
    appId: '1:338750312653:android:d0febff6a1aeb925415984',
    messagingSenderId: '338750312653',
    projectId: 'chat-83727',
    storageBucket: 'chat-83727.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbD_LWD4liNI70T-4nuvlSiyef7bVTzXs',
    appId: '1:338750312653:ios:5b0b73e92bba3ff4415984',
    messagingSenderId: '338750312653',
    projectId: 'chat-83727',
    storageBucket: 'chat-83727.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbD_LWD4liNI70T-4nuvlSiyef7bVTzXs',
    appId: '1:338750312653:ios:5b0b73e92bba3ff4415984',
    messagingSenderId: '338750312653',
    projectId: 'chat-83727',
    storageBucket: 'chat-83727.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );
}
